export const buttonsb = {
    colors: {
        // new design system colors
        interactive100: '#575CFE',
        interactive50: '#878BFC',
        interactive30: '#D8D9FE',
        interactive10: '#EDEDFF',
        primary100: '#25273D',
        primary60: '#626472',
        primary30: '#80818A',
        secondary100: '#E6E9EB',
        secondary60: '#F1F3F4',
        neutral10: '#FFFFFF',
        neutral20: '#EAEAEA',
        neutral30: '#F3F7F9',
        neutral60: '#BEC9D0',
        neutral70: '#A8A9B1',
        neutral80: '#787A9B',
        success100: '#1AAB9B',
        success10: '#E7FCFA',
        warning100: '#D8762D',
        warning10: '#FFF1CF',
        critical100: '#D94A1E',
        critical10: '#FFEEE9',
    fonts: {
        body: '"Inter", "Helvetica Neue", sans-serif',
        heading: '"Inter", "Helvetica Neue", sans-serif',
        monospace: 'monospace',
      },
      //           0   1   2   3   4   5   6   7   8   9  10
      fontSizes: [10, 12, 14, 16, 18, 20, 24, 32, 52, 64, 96],
      fontWeights: {
        regular: 400,
        medium: 500,
        semiBold: 600,
        bold: 700,
      },
      lineHeights: {
        body: 1.5,
        bodyLoose: 1.7,
        tight: 1.05,
        loose: 1.35,
        //
        buttons: '2.1em',
        secondaryButton: 0.8,
        smallButton: 1.9,
      },
      text: {
        header1: {
          fontFamily: 'heading',
          fontWeight: 'medium',
          lineHeight: '54px',
          fontSize: '52px',
          letterSpacing: '-0.02em',
          color: 'primary100',
        },
        header2: {
          fontFamily: 'heading',
          fontWeight: 'medium',
          lineHeight: '54px',
          fontSize: '40px',
          letterSpacing: '-0.02em',
          color: 'primary100',
        },
        header3: {
          fontFamily: 'heading',
          fontWeight: 'medium',
          lineHeight: '42px',
          fontSize: '32px',
          color: 'primary100',
        },
        header4: {
          fontFamily: 'heading',
          fontWeight: 'semiBold',
          lineHeight: '40px',
          fontSize: '28px',
          color: 'primary100',
        },
        header5: {
          fontFamily: 'heading',
          fontWeight: 'semiBold',
          lineHeight: '32px',
          fontSize: '20px',
          color: 'primary100',
        },
        paragraph1: {
          fontFamily: 'body',
          lineHeight: '28px',
          fontSize: '18px',
          color: 'primary100',
        },
        boldParagraph1: {
          fontFamily: 'body',
          lineHeight: '28px',
          fontWeight: 'semiBold',
          fontSize: '18px',
          color: 'primary100',
        },
        paragraph2: {
          fontFamily: 'body',
    
          lineHeight: '24px',
          fontSize: '16px',
          color: 'primary100',
        },
        boldParagraph2: {
          fontFamily: 'body',
          fontWeight: 'semiBold',
          lineHeight: '24px',
          fontSize: '16px',
          color: 'primary100',
        },
        paragraph3: {
          fontFamily: 'body',
    
          lineHeight: '22px',
          fontSize: '14px',
          color: 'primary100',
        },
        boldParagraph3: {
          fontFamily: 'body',
          fontWeight: 'semiBold',
          lineHeight: '22px',
          fontSize: '14px',
          color: 'primary100',
        },
        paragraph4: {
          fontFamily: 'body',
          fontWeight: 'semiBold',
          lineHeight: '20px',
          fontSize: '12px',
          color: 'primary100',
        },
      },
    primary: {
      variant: 'text.paragraph1',
      cursor: 'pointer',
      fontWeight: 'semiBold',
      borderRadius: 'round',
      lineHeight: 'buttons',
      color: 'neutral10',
      transition: 'background 200ms',
      '&:hover, &:focus-visible': {
        bg: 'primary60',
      },
      '&:disabled': {
        bg: 'neutral60',
        pointerEvents: 'none',
      },
      '&:focus': {
        outline: 'none',
      },
    },
    outline: {
      variant: 'text.paragraph2',
      cursor: 'pointer',
      background: 'none',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'secondary100',
      borderRadius: 'round',
      color: 'primary100',
      fontWeight: 'semiBold',
      px: 4,
      py: 2,
      '&:focus': {
        outline: 'none',
      },
      '&:disabled': {
        pointerEvents: 'none',
        opacity: 0.5,
      },
    },
    outlineSquare: {
      variant: 'text.paragraph2',
      background: 'none',
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'secondary100',
      borderRadius: 'mediumLarge',
      '&:focus': {
        outline: 'none',
      },
    },
    secondary: {
      variant: 'text.paragraph3',
      whiteSpace: 'nowrap',
      cursor: 'pointer',
      fontWeight: 'semiBold',
      bg: 'secondary60',
      color: 'primary100',
      borderRadius: 'round',
      px: 4,
      py: 2,
      transition: 'background-color 200ms',
      '&:focus': {
        outline: 'none',
      },
      '&:disabled': {
        pointerEvents: 'none',
        opacity: 0.5,
      },
      '&:hover': {
        backgroundColor: 'secondary100',
      },
    },
    tertiary: {
      variant: 'text.paragraph3',
      px: '24px',
      py: 2,
      fontSize: 1,
      fontWeight: 'semiBold',
      lineHeight: '20px',
      cursor: 'pointer',
      bg: 'secondary60',
      color: 'primary100',
      borderRadius: 'round',
      whiteSpace: 'nowrap',
      transition: 'background-color 200ms, border-color 200ms',
      '&:hover': {
        bg: 'secondary100',
      },
      '&:focus': {
        outline: 'none',
      },
      '&:disabled': {
        pointerEvents: 'none',
        opacity: 0.5,
      },
    },
    action: {
      variant: 'buttons.tertiary',
      bg: 'neutral10',
      border: '1px solid',
      borderColor: 'neutral20',
      borderRadius: 'rounder',
      '&:hover': {
        bg: 'neutral10',
        borderColor: 'primary100',
      },
    },
    actionActiveGreen: {
      variant: 'buttons.tertiary',
      bg: 'success100',
      color: 'neutral10',
      '&:hover': {
        bg: 'success100',
      },
    },
    square: {
      variant: 'text.paragraph2',
      bg: 'white',
      borderRadius: 'large',
      py: 3,
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: 'secondary100',
      '&:focus': {
        outline: 'none',
      },
      '&:focus-visible': {
        boxShadow: 'surface',
      },
    },
    expandable: {
      variant: 'text.header3',
      width: '100%',
      background: 'none',
      textAlign: 'left',
      cursor: 'pointer',
      p: 0,
      py: 4,
      ':hover': {
        opacity: 0.7,
      },
      ':focus': {
        outline: 'none',
      },
    },
    tableHeader: {
      variant: 'text.tableHead',
      background: 'none',
      p: 0,
      cursor: 'pointer',
      ':focus': {
        outline: 'none',
      },
      '&:focus-visible': {
        textDecoration: 'underline',
      },
    },
    filter: {
      borderRadius: 'round',
      background: 'none',
      color: 'neutral80',
      fontFamily: 'body',
      fontWeight: 'semiBold',
      cursor: 'pointer',
      boxSizing: 'border-box',
      border: '1px solid transparent',
      px: 4,
      transition: 'borderColor ease-in 0.3s, color ease-in 0.3s',
      font: '',
      ':focus': {
        outline: 'none',
      },
      '&:focus-visible': {
        textDecoration: 'underline',
      },
      '&[data-selected="true"]': {
        border: 'light',
        color: 'primary100',
      },
    },
    textual: {
      variant: 'text.paragraph3',
      fontWeight: 'semiBold',
      color: 'interactive100',
      cursor: 'pointer',
      background: 'none',
      transition: 'opacity 200ms',
      '&:hover, &:focus-visible': {
        opacity: 0.7,
      },
      '&:focus': {
        outline: 'none',
      },
      '&:disabled': {
        opacity: 0.5,
      },
    },
    textualSmall: {
      variant: 'buttons.textual',
      fontSize: 1,
      color: 'primary100',
      py: 0,
    },
    actionOption: {
      fontFamily: 'body',
      width: '100%',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      cursor: 'pointer',
      fontSize: 1,
      fontWeight: 'semiBold',
      color: 'primary100',
      userSelect: 'none',
      bg: 'secondary60',
      px: 2,
      py: 1,
      borderRadius: 'round',
      lineHeight: 1.25,
      position: 'relative',
      '&:hover': {
        bg: 'secondary100',
      },
      transition: 'background-color 200ms',
    },
    actionOptionOpened: {
      variant: 'buttons.actionOption',
      borderRadius: 'mediumLarge',
      borderBottomLeftRadius: '0px',
      borderBottomRightRadius: '0px',
    },
    bean: {
      variant: 'buttons.actionOption',
      px: 3,
      py: 2,
      width: 'initial',
    },
    beanActive: {
      variant: 'buttons.bean',
      color: 'white',
      bg: 'primary100',
      '&:hover': {
        color: 'white',
        bg: 'primary100',
      },
    },
    vaultEditingController: {
      fontFamily: 'body',
      fontSize: 3,
      fontWeight: 'semiBold',
      lineHeight: 'body',
      bg: 'neutral10',
      p: 3,
      color: 'primary100',
      boxShadow: 'vaultEditingController',
      borderRadius: 'inherit',
      cursor: 'pointer',
    },
    vaultEditingControllerInactive: {
      fontFamily: 'body',
      fontSize: 3,
      fontWeight: 'semiBold',
      bg: 'transparent',
      color: 'neutral80',
      cursor: 'pointer',
      transition: '150ms cubic-bezier(0.215,0.61,0.355,1)',
      '&:hover': {
        color: 'primary100',
      },
    },
    tab: {
      display: 'flex',
      alignItems: 'center',
      fontFamily: 'body',
      fontWeight: 'semiBold',
      lineHeight: 'body',
      bg: 'transparent',
      color: 'neutral80',
      cursor: 'pointer',
      transition: '150ms cubic-bezier(0.215,0.61,0.355,1)',
    },
    menuButton: {
      variant: 'buttons.secondary',
      bg: 'neutral10',
      boxShadow: 'buttonMenu',
      fontSize: [1, 2],
      minHeight: ['40px', 'auto'],
      ':hover': {
        boxShadow: 'selectMenu',
      },
      transition: '150ms cubic-bezier(0.215,0.61,0.355,1)',
    },
    menuButtonRound: {
      variant: 'buttons.menuButton',
      width: '50px',
      height: '50px',
      padding: 0,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      flexShrink: 0,
    },
    unStyled: {
      background: 'unset',
      border: 'unset',
      color: 'inherit',
      cursor: 'pointer',
      fontFamily: 'body',
    },
    actionActive: {
      variant: 'buttons.action',
      borderColor: 'primary100',
    },
    pill: {
      px: '24px',
      py: '12px',
      color: 'neutral80',
      fontFamily: 'body',
      fontSize: 3,
      fontWeight: 'semiBold',
      lineHeight: 'heading',
      border: 'none',
      borderRadius: 'round',
      backgroundColor: 'transparent',
      cursor: 'pointer',
      '&:hover': {
        backgroundColor: 'neutral20',
      },
      transition: 'color 200ms, background-color 200ms',
    },
    pillActive: {
      variant: 'buttons.pill',
      color: 'neutral10',
      backgroundColor: 'interactive100',
      '&:hover': {
        backgroundColor: 'interactive100',
      },
    },
    networkPicker: {
      backgroundColor: 'transparent',
      color: 'primary100',
      display: 'flex',
      justifyContent: 'flex-start',
      alignItems: 'center',
      position: 'relative',
      fontSize: '14px',
      padding: 2,
      cursor: 'pointer',
      '&:disabled': {
        opacity: 0.5,
        cursor: 'not-allowed',
      },
    },
},
};