/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DsSpell__factory } from "./DsSpell__factory";
export { VoteDelegate__factory } from "./VoteDelegate__factory";
export { VoteProxy__factory } from "./VoteProxy__factory";
